version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: ./nextjs-with-typescript
      dockerfile: Dockerfile
    volumes:
      - ./nextjs-with-typescript:/usr/src/app
      # Prevent the node_modules and .next folders in the Docker container from being accidentally overwritten with our initial mapping of our local directory to /usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    # env_file:
    #   - .env
