version: "3.3"

services:
  nextjs:
    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: ./nextjs-with-typescript
      dockerfile: Dockerfile
    volumes:
      - ./nextjs-with-typescript:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    # env_file:
    #   - .env
